### ISSUE TITLE
Can this repo be used in multi thread?

### ISSUE THREAD

**Issue by zh794390558** [iver56/audiomentations#46] opened 2020-07-20 08:36 UTC
I encountered this error, which caused by TimeMask
```text
time mask: t0 138974  t: 21416  m.shpae: (21416,)  newshpae: (93184,)  rawshpae: (93184,)  slice shape: (0,)
err:  operands could not be broadcast together with shapes (0,) (21416,) (0,) 
```

```
augmenter = Compose([
        TimeStretch(min_rate=0.8, max_rate=1.25, p=1.0),
        AddGaussianNoise(min_amplitude=0.001, max_amplitude=0.015, p=0.2),
        PitchShift(min_semitones=-4, max_semitones=4, p=0.2),
        Shift(min_fraction=-0.5, max_fraction=0.5, p=0.2),
        FrequencyMask(min_frequency_band=0.0, max_frequency_band=0.5, p=0.2),
        TimeMask(min_band_part=0.0, max_band_part=0.5, fade=False, p=0.2)
], p=1.0, shuffle=False)

def aug_sample(samples, sample_rate):
  assert samples.dtype == np.int16 
  samples =  samples * max(0.01, np.max(np.abs(samples))) / 32768.0
  samples = samples.astype(np.float32)
  samples = augmenter(samples=samples, sample_rate=sample_rate)
  samples *= 32767 / max(0.01, np.max(np.abs(samples)))
  samples = samples.astype(np.int16)
  return samples
```

using `aug_sample` to load wav by `threading.Thread` like mapreduce.

**Comment by iver56** [comment] 2020-07-22 18:17
Hi Hui Zhang, and thanks for your interest in audiomentations! Do you get the same error message if you don't use threading? Ideally, audiomentations should support multi-threads, but I don't have any tests for that currently. If you would like to contribute such a test, that would be appreciated!

**Comment by zh794390558** [comment] 2020-07-24 08:27
one `augmenter`  object can not be called by multi-thread.

**Comment by iver56** [comment] 2020-08-25 13:15
Ok, in that case I should investigate how that can be fixed. Maybe it needs to be picklable?

Which operating system are you using? Windows?

**Comment by zh794390558** [comment] 2020-08-26 02:01
I using centos 7.

**Comment by francislata** [comment] 2020-09-21 16:27
@iver56 - Any updates on this? Currently, I'm using this module to augment a clean audio in the `collate_fn` but its the bottleneck on producing augmented audio with IR and background noise. The reason why I'm doing this on the fly is to give equal probability to all possible clean audio + IR + background noise combinations.

Thank you!

**Comment by iver56** [comment] 2020-09-21 18:44
Hi francislata. No progress on multiprocessing support lately. I want to support it though. My time is limited. If you want to contribute, that would be welcome.

I spent some time looking into applying IR with Pytorch today though. More info on that might appear here later: https://github.com/asteroid-team/torch-audiomentations

**Comment by iver56** [comment] 2020-09-22 09:39
@francislata Execution time of IR convolution can be sped up with GPU. See the plot here:

https://github.com/asteroid-team/torch-audiomentations#readme

**Comment by francislata** [comment] 2020-09-22 13:29
@iver56 This is very interesting. I started taking a look at it but will keep going at it. From what I can tell initially, it looks like using the `torch` module to perform such augmentations, we can take advantage of the GPU support.

**Comment by iver56** [comment] 2020-12-10 13:47
@zh794390558 Can you post a more complete code snippet to reproduce this problem? It should include the part with `threading.Thread`

**Comment by atamazian** [comment] 2022-05-20 14:24
This issue is dormant for quite some time. I suggest to close it - if necessary, it can be reopened.

**Comment by iver56** [comment] 2022-05-23 06:39
Yeah, I actually think multithreading works fine now. I've been using it for some time without problems. It's just that I have no unit tests for it 😕
I can close this and then reopen another issue for adding multithreading/multiprocessing tests

**Closed by iver56** 2022-05-23 06:39 UTC

**Comment by worldveil** [comment] 2026-01-19 17:37
For folks coming here looking to speed up augmentations, I have a PR [here](https://github.com/iver56/audiomentations/pull/419) that can accelerate applying background noise and impulse responses via a shared cache.
